### PR TITLE
A new version that optimize IO operation. Stringent API...

### PR DESCRIPTION
**Pull request by kmvan**
I rewrite all codes and optimize the IO operation. 
And uses more stringent API.
All return data is ARRAY object.

### CODE REVIEW

**Comment by kmvan** [comment]
not complete, do not merge now.

**Comment by bencagri** [comment]
ok kmvan.

**Comment by kmvan** [comment]
hi，@bencagri. I meet a problem, and I think my ability is not enough to complete it.
About the multi condition select (Trigeminal / N  search tree?).
For example:

``` php
<?php
/** demo datas */
$datas = [
    'people1' => [
        'name' => 'john',
        'age' => 48,
        'sex' => 'male',
    ],
    'people12' => [
        'name' => 'mike',
        'age' => 8,
        'sex' => 'male',
        'fav' => [
            'apple', 'water', 'ona'
        ]
    ]
    'people3' => [
        'name' => 'jack',
        'age' => 8,
        'sex' => 'female',
        'fav' => [
            'big apple', 'water', 'ona'
        ]
    ]
];
/**
 * Select - demo function
 * 
 * @param array $datas Database datas
 * @param array $args Search conditions
 */
function select(array $datas, array $args){
    /** ...how to code here XD.. */
}

/** If I want to search Jack by some conditions (age is 8 and sex is female) */
var_dump(select( $datas, [
    'relation' => 'and', /** maybe use 'or', means age is 8 or sex is female */
    'age' => 8,
    'sex' => 'female'
]));
```

I am so sorry that the function select I have no idea how to complete it.
How about your idea?

**Comment by bencagri** [comment]
I will check it out when im home.

**Comment by kmvan** [comment]
Thank you very much :+1:  Let us complete it together.

**Comment by bencagri** [comment]
this function seems useful ;)

```
function select($array, $search){
// Create the result array
$result = array();
// Iterate over each array element
foreach ($array as $key => $value)
{
  // Iterate over each search condition
  foreach ($search as $k => $v)
  {
    // If the array element does not meet the search condition then continue to the next element
    if (!isset($value[$k]) || $value[$k] != $v)
    {
      continue 2;
    }
  }
  // Add the array element's key to the result array
  $result[] = $key;
}
// Return the result array
return $result;
}
```

source : http://stackoverflow.com/a/13943171/2185524

**Pull request closed without merging**
